[mypy]
plugins =
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "bde.settings"

[mypy-bde.migrations.*]
ignore_errors = True

[mypy-members.migrations.*]
ignore_errors = True

[mypy-showcase.migrations.*]
ignore_errors = True
