[mypy]
plugins =
    mypy_django_plugin.main

strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unused_configs = True
warn_return_any = True
warn_unreachable = True

ignore_missing_imports = False
disallow_untyped_defs = False
check_untyped_defs = True

[mypy.plugins.django-stubs]
django_settings_module = "bde.settings"

[mypy-bde.migrations.*]
ignore_errors = True

[mypy-members.migrations.*]
ignore_errors = True

[mypy-showcase.migrations.*]
ignore_errors = True
[mypy-*.tests]
disable_error_code = attr-defined

