# Generated by Django 5.2.6 on 2026-09-25 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_setting_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, help_text="Le titre de la page qui s'affiche en haut de la page.", max_length=200)),
                ('description', models.TextField(blank=True, help_text="La description de la page qui s'affiche en haut de la page et dans les cartes d'aperçu.")),
                ('under_construction', models.BooleanField(default=False, help_text="Cochez cette case si la page est en construction. Cela affichera un message d'information aux visiteurs.")),
                ('seo_title', models.CharField(blank=True, help_text="Le titre SEO de la page sert à améliorer le référencement et l'affichage dans les résultats de recherche.", max_length=200)),
                ('seo_description', models.TextField(blank=True, help_text="La description SEO de la page sert à améliorer le référencement et l'affichage dans les résultats de recherche.")),
                ('seo_canonical_url', models.CharField(blank=True, help_text="Laisser vide pour utiliser l'URL canonique par défaut de la page.", max_length=500)),
                ('seo_og_title', models.CharField(blank=True, help_text='Laisser vide pour utiliser le titre SEO.', max_length=200)),
                ('seo_og_description', models.TextField(blank=True, help_text='Laisser vide pour utiliser la description SEO.')),
                ('seo_og_type', models.CharField(blank=True, default='website', help_text="Type d'objet Open Graph (ex: 'website', 'article', etc.).", max_length=50)),
                ('seo_og_image', models.CharField(blank=True, help_text="URL de l'image Open Graph. Laisser vide pour utiliser l'image par défaut du site.", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TextArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Le contenu de la zone de texte. Vous pouvez utiliser du HTML pour formater le texte.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textareas', to='core.page')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_textarea_page_key')],
            },
        ),
    ]
