# Generated by Django 5.2.6 on 2025-09-13 09:13

import showcase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to=showcase.models.Partner._partner_picture_upload_to)),
                ('url', models.URLField(blank=True, null=True)),
                ('enable', models.BooleanField(default=False, help_text='Afficher/Cacher le partenaire')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=showcase.models.News._news_picture_upload_to)),
                ('url', models.URLField(blank=True, null=True)),
                ('enable', models.BooleanField(default=False, help_text="Afficher/Cacher l'actualité")),
                ('teams', models.ManyToManyField(blank=True, related_name='news_teams', to='members.team')),
            ],
        ),
    ]
