# Generated by Django 5.2.6 on 2026-02-23 20:02

import showcase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to=showcase.models.Partner._partner_picture_upload_to)),
                ('url', models.URLField(blank=True, null=True)),
                ('enable', models.BooleanField(default=False, help_text='Afficher/Cacher le partenaire')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
