# Generated by Django 5.2.6 on 2026-02-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_bdeemail_usefulcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDEPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
