# Generated by Django 5.2.6 on 2025-09-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userteam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.team'),
            preserve_default=False,
        ),
    ]
