# Generated by Django 5.2.6 on 2026-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_userteam_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='feminine_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-Président'), ('SECRETARY', 'Secrétaire'), ('TREASURER', 'Trésorier'), ('VICE_TREASURER', 'Vice-Trésorier'), ('MANAGER', 'Responsable'), ('MEMBER', 'Membre')], default='MEMBER', max_length=20),
        ),
    ]
