# Generated by Django 5.2.6 on 2026-03-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userprofile_feminine_role_alter_userteam_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('TREASURER', 'Trésorier'), ('VICE_TREASURER', 'Vice-Trésorier'), ('VICE_PRESIDENT', 'Vice-Président'), ('SECRETARY', 'Secrétaire'), ('MANAGER', 'Responsable'), ('MEMBER', 'Membre')], default='MEMBER', max_length=20),
        ),
    ]
